name: Food-Order
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
     db:
      condition: service_healthy
    environment:
     SPRING_PROFILES_ACTIVE: docker
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Orders?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: pranish24
  kafka:
   image: apache/kafka:latest
   container_name: kafka
   environment:
    KAFKA_NODE_ID: 1
    KAFKA_PROCESS_ROLES: broker,controller
    KAFKA_LISTENERS: BROKER://:9092,CONTROLLER://:9093
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
    KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:9092
    KAFKA_CLUSTER_ID: "kafka-1"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_NUM_PARTITIONS: 1
   ports:
     - "9092:9092"
  db:
    image: mysql:8.0.44-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pranish24
      MYSQL_DATABASE: Orders
    ports:
      - "3306:3306"
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 5s
     timeout: 5s
     retries: 10
    volumes:
     - mysql-data:/var/lib/mysql



volumes:
  mysql-data:

